export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
// src/app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Ignore any client-only attribute differences injected into <body> */}
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
